#!/bin/bash

export NAME_SYN=name_syn
export TM_RDR=2

(

	echo "<h2>Celkové pořadí se škrtáním (oficiální)</h2>"
	DR_MAX=3 ../utils/c_total 01 02 03 04 05 | ../utils/hconv_score
	echo

	echo "<h2>Celkové pořadí bez škrtání</h2>"
	../utils/c_total 01 02 03 04 05 | ../utils/hconv_score
	echo

	echo "<h2>Umístění v závodech</h2>"
	echo "<table border=1>"
	echo "<tr><th>Jezdec</th><th><a href=\"redir/race.php?season=2001&amp;race=01\">M-Palác, 30. 5.</a></th><th><a href=\"redir/race.php?season=2001&amp;race=02\">M-Palác, 27. 6.</a></th><th><a href=\"redir/race.php?season=2001&amp;race=03\">Radotín, 19. 8.</a></th><th><a href=\"redir/race.php?season=2001&amp;race=04\">Modřice, 27. 9.</a></th><th><a href=\"redir/race.php?season=2001&amp;race=05\">Radotín, 15. 12.</a></th><th>Body se škrtáním</th><th>Škrtnuto</th><th>Body celkem</th></tr>"
	DR_MAX=3 ../utils/gen_seastab 01 02 03 04 05
	echo "</table>"
	echo

	cat<<_TAIL_
<h2>Pole positions</h2>
<table border=1>
<tr><td>Krysa von Ratteburg</td><td>2</td></tr>
<tr><td>T-Rex</td><td>1</td></tr>
<tr><td>Fija</td><td>1</td></tr>
<tr><td>Kobdzey</td><td>1</td></tr>
</table>

<h2>Nejrychlejší kola</h2>
<table border=1>
<tr><td>Krysa von Ratteburg</td><td>3</td></tr>
<tr><td>T-Rex</td><td>1</td></tr>
<tr><td>Kobdzey</td><td>1</td></tr>
</table>
_TAIL_

) > stats.html
